---

- name: Create a group for jenkins user on salve
  group:
    name: "{{ slave_username }}"
    state: present
  become: True

- name: Create jenkins user on slave
  user:
    name: "{{ slave_username }}"
    group: "{{ slave_username }}"
    password: "{{ slave_password | password_hash('sha512', \
               65534 | random(seed=inventory_hostname) | string) }}"
    update_password: always
    state: present
    append: True
    createhome: True
  become: True

