---   
    - name: Install JAVA JDK
      yum:
        name: java-1.8.0-openjdk, java-1.8.0-openjdk-devel 
      become: yes
    - name:  jenkins.repo Installation
      get_url:
        url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
      become: yes
    - name: Import Jenkins Key
      rpm_key:
        state: present
        key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
      become: yes
    - name: Install Jenkins
      yum:
        name: jenkins
        state: present
      become: yes
    - name: Change Jenkins JAVA options
      lineinfile: 
        dest=/etc/sysconfig/jenkins
        regexp=^JENKINS_JAVA_OPTIONS=
        line=JENKINS_JAVA_OPTIONS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"
      become: true

    - name: Start and Enable Jenkins
      systemd:
        name: jenkins
        state: started
        enabled: true
      become: yes
      
#    - name: Sleep for 30 seconds and continue with play
#      wait_for: timeout=30
#
#    - name: Get init password Jenkins
#      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
#      changed_when: false
#      register: result
#      become: yes
#    - name: Print init password Jenkins
#      debug:
#        var: result.stdout
#      become: yes
    - name: Create initialization scripts directory
      file: path=/var/lib/jenkins/init.groovy.d
            state=directory
            owner=jenkins
            group=jenkins
            mode=0775
      become: yes        

    - name: Add initialization script to setup basic security
      template: src=security.groovy.j2
                dest=/var/lib/jenkins/init.groovy.d/security.groovy
      become: yes

#    - name: Install plugin
#      jenkins_plugin:
#        name: build-pipeline-plugin
#        url_username: "{{ jenkins_admin_username }}"
#        url_password: "{{ jenkins_admin_password }}"
#        url: http://127.0.0.1:8081

    - name: Start Jenkins service
      service:
        name=jenkins
        state=restarted
      become: yes
    - name: Wait for Jenkins to start up
      uri:
        url: http://localhost:8080
        status_code: 200
        user: "{{ jenkins_admin_username }}"
        password: "{{ jenkins_admin_password }}"
        timeout: 5
        force_basic_auth: yes
      register: jenkins_service_status
      retries: 10
      delay: 7
      until: >
         'status' in jenkins_service_status and
         jenkins_service_status['status'] == 200
    - name: Check Jenkins status
      debug:
        msg: "Jenkins status: {{ jenkins_service_status['status'] }}"
#    - name: Install Jenkins plugins
#      jenkins_plugin:
#        name: build-pipeline-plugin
#        url_username: "{{ jenkins_admin_username }}"
#        url_password: "{{ jenkins_admin_password }}"
#        state: present
#      delay: 10    
